from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON
revision="0001_initial";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
    op.create_table("users",sa.Column("id",sa.Integer,primary_key=True),sa.Column("username",sa.String(50),unique=True,nullable=False),sa.Column("email",sa.String(255),unique=True,nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("is_active",sa.Boolean,nullable=False,server_default=sa.true()))
    op.create_index("ix_users_username","users",["username"]);op.create_index("ix_users_email","users",["email"])
    op.create_table("categories",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE")),sa.Column("name",sa.String(80),nullable=False),sa.Column("is_default",sa.Boolean,nullable=False,server_default=sa.false()))
    op.create_index("ix_categories_user_id","categories",["user_id"])
    op.create_table("achievements",sa.Column("id",sa.Integer,primary_key=True),sa.Column("code",sa.String(50),unique=True,nullable=False),sa.Column("name",sa.String(100),nullable=False),sa.Column("description",sa.String(255),nullable=False),sa.Column("xp",sa.Integer,nullable=False),sa.Column("badge",sa.String(100)))
    op.create_table("habits",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("category_id",sa.Integer,sa.ForeignKey("categories.id",ondelete="SET NULL")),sa.Column("name",sa.String(120),nullable=False),sa.Column("description",sa.Text),sa.Column("frequency",sa.Enum("DAILY","WEEKLY","CUSTOM",name="frequency_enum"),nullable=False),sa.Column("target_days",JSON,nullable=False),sa.Column("reminder_time",sa.Time),sa.Column("start_date",sa.Date,nullable=False),sa.Column("end_date",sa.Date),sa.Column("priority",sa.Enum("LOW","MEDIUM","HIGH",name="priority_enum"),nullable=False),sa.Column("color",sa.String(20)),sa.Column("icon",sa.String(50)),sa.Column("target_value",sa.Float),sa.Column("unit",sa.String(30)),sa.Column("active",sa.Boolean,nullable=False),sa.Column("archived",sa.Boolean,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_habits_user_id","habits",["user_id"])
    op.create_table("habit_completions",sa.Column("id",sa.Integer,primary_key=True),sa.Column("habit_id",sa.Integer,sa.ForeignKey("habits.id",ondelete="CASCADE"),nullable=False),sa.Column("completion_date",sa.Date,nullable=False),sa.Column("actual_value",sa.Float),sa.Column("notes",sa.Text),sa.Column("completed_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("habit_id","completion_date",name="uq_habit_completion_date"))
    op.create_index("ix_habit_completions_habit_id","habit_completions",["habit_id"]);op.create_index("ix_habit_completions_completion_date","habit_completions",["completion_date"])
    op.create_table("habit_goals",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("habit_id",sa.Integer,sa.ForeignKey("habits.id",ondelete="CASCADE"),unique=True,nullable=False),sa.Column("target_value",sa.Float,nullable=False),sa.Column("unit",sa.String(30)),sa.Column("active",sa.Boolean,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("reminders",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("habit_id",sa.Integer,sa.ForeignKey("habits.id",ondelete="CASCADE"),nullable=False),sa.Column("enabled",sa.Boolean,nullable=False),sa.Column("reminder_time",sa.Time,nullable=False),sa.Column("reminder_days",JSON,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_reminders_user_id","reminders",["user_id"]);op.create_index("ix_reminders_habit_id","reminders",["habit_id"])
    op.create_table("recommendations",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("habit_id",sa.Integer,sa.ForeignKey("habits.id",ondelete="CASCADE")),sa.Column("type",sa.Enum("TARGET_ADJUSTMENT","REMINDER_TIME","SCHEDULE_CHANGE","HABIT_PRIORITY","HABIT_SIMPLIFICATION","HABIT_RECOVERY","NEW_HABIT","HABIT_OVERLOAD","CATEGORY_FOCUS","WEEKLY_PLAN","MONTHLY_PLAN",name="recommendation_type_enum"),nullable=False),sa.Column("priority",sa.String(10),nullable=False),sa.Column("confidence",sa.String(10),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("reason",sa.Text,nullable=False),sa.Column("expected_benefit",sa.Text,nullable=False),sa.Column("action",sa.Text,nullable=False),sa.Column("status",sa.Enum("PENDING","ACCEPTED","REJECTED",name="recommendation_status_enum"),nullable=False),sa.Column("baseline_rate",sa.Float),sa.Column("outcome_rate",sa.Float),sa.Column("outcome_checked_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_recommendations_user_id","recommendations",["user_id"])
    op.create_table("ai_insights",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("insight_type",sa.String(40),nullable=False),sa.Column("content",JSON,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_ai_insights_user_id","ai_insights",["user_id"])
    op.create_table("user_achievements",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("achievement_id",sa.Integer,sa.ForeignKey("achievements.id",ondelete="CASCADE"),nullable=False),sa.Column("unlocked_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for t in ["user_achievements","ai_insights","recommendations","reminders","habit_goals","habit_completions","habits","achievements","categories","users"]:
        op.drop_table(t)
    op.execute("DROP TYPE IF EXISTS recommendation_status_enum")
    op.execute("DROP TYPE IF EXISTS recommendation_type_enum")
    op.execute("DROP TYPE IF EXISTS priority_enum")
    op.execute("DROP TYPE IF EXISTS frequency_enum")
